//! Interoperability with the former Python implementation: keys, mandates, a
//! revocation list, a registry store and an audit log written by the Python CLI
//! (`tests/fixtures/interop/interop.json`, regenerated by `generate.sh` next to it)
//! are accepted and extended by the Rust CLI and library.
//!
//! The other direction (Rust output read by Python) was checked once while both
//! implementations coexisted; it cannot be kept as a test without Python.

mod common;

use std::path::Path;

use tokencrumb_mcp_proxy::audit::{
    AuditLog, Record, TrustedKeys, trusted_from, verify_head_attestation, verify_log,
};
use tokencrumb_mcp_proxy::biscuit_ops as ops;
use tokencrumb_mcp_proxy::json::strict_json;
use tokencrumb_mcp_proxy::keys;
use tokencrumb_mcp_proxy::policy::parse_policy;
use tokencrumb_mcp_proxy::registry::Store;
use tokencrumb_mcp_proxy::revocation::validate_document;
use tokencrumb_mcp_proxy::verifier::{Headers, Verifier, VerifierOptions};
use common::{bm, stderr, stdout};
use serde_json::{Value, json};

const AUDIENCE: &str = "interop-gw";

/// The Python-written files, unpacked into a fresh directory.
fn fixtures() -> (tempfile::TempDir, Value) {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/interop/interop.json");
    let bundle: Value = serde_json::from_slice(&std::fs::read(path).unwrap()).unwrap();
    let dir = tempfile::tempdir().unwrap();
    for (name, content) in bundle["files"].as_object().unwrap() {
        std::fs::write(dir.path().join(name), content.as_str().unwrap()).unwrap();
    }
    (dir, bundle)
}

fn read(dir: &Path, name: &str) -> String {
    std::fs::read_to_string(dir.join(name))
        .unwrap()
        .trim()
        .to_owned()
}

fn verifier(authority_pub: &str) -> Verifier {
    // The fixtures are long-lived so they stay valid; the ceiling is raised to match.
    let mut policy = parse_policy(&json!({
        "max_ttl": "4000d",
        "tools": [{
            "name": "read_file",
            "operation": "read",
            "resource": {"from": "arguments.path"},
            "args": [{"from": "arguments.incident_id", "as": "incident_id"}],
        }],
    }))
    .unwrap();
    policy.policy_digest = "interop".into();
    Verifier::new(authority_pub, policy, VerifierOptions::new(AUDIENCE)).unwrap()
}

fn allowed(v: &Verifier, token: &str, path: &str, incident: &str) -> bool {
    let headers = Headers::new([("authorization", format!("Biscuit {token}"))]);
    v.verify_call(
        "read_file",
        &json!({"path": path, "incident_id": incident}),
        &headers,
        None,
        None,
    )
    .unwrap()
    .allow
}

#[test]
fn python_keys_load_including_an_encrypted_one() {
    let (dir, bundle) = fixtures();
    let authority = keys::load_private_key(dir.path().join("authority.key"), None).unwrap();
    assert_eq!(
        keys::public_from_private(&authority).unwrap(),
        read(dir.path(), "authority.pub")
    );
    let passphrase = bundle["passphrase"].as_str().unwrap();
    let agent = keys::load_private_key(dir.path().join("agent.key"), Some(passphrase)).unwrap();
    assert_eq!(
        keys::public_from_private(&agent).unwrap(),
        read(dir.path(), "agent.pub")
    );
    assert!(keys::load_private_key(dir.path().join("agent.key"), Some("wrong")).is_err());
}

#[test]
fn python_mandates_are_inspected_verified_and_attenuated_by_rust() {
    let (dir, _) = fixtures();
    let authority_pub = read(dir.path(), "authority.pub");
    let mandate = read(dir.path(), "mandate.b64");
    let narrowed = read(dir.path(), "narrowed.b64");

    let output = bm(dir.path(), &["inspect", "mandate.b64"]);
    assert!(output.status.success(), "{}", stderr(&output));
    let text = stdout(&output);
    for row in [
        ["│", "agent_id", "interop-agent", "│"],
        ["│", "audience", AUDIENCE, "│"],
        ["│", "required_profile", "native", "│"],
    ] {
        assert!(
            text.lines()
                .any(|l| l.split_whitespace().collect::<Vec<_>>() == row),
            "{row:?} in\n{text}"
        );
    }
    assert!(text.contains("assigned_incident(\"INC-1\");"));
    let hardened = stdout(&bm(dir.path(), &["inspect", "hardened.b64"]));
    assert!(hardened.contains(&read(dir.path(), "agent.pub")));

    let v = verifier(&authority_pub);
    assert!(allowed(&v, &mandate, "/projets/acme/a.txt", "INC-1"));
    assert!(!allowed(&v, &mandate, "/projets/acme/a.txt", "INC-2"));
    assert!(!allowed(&v, &mandate, "/etc/passwd", "INC-1"));
    // Python's own attenuation narrows as signed.
    assert_eq!(ops::min_budget_cap(&narrowed).unwrap(), Some(5));
    assert!(!allowed(&v, &narrowed, "/projets/acme/a.txt", "INC-1"));
    assert!(allowed(&v, &narrowed, "/projets/acme/docs/a.txt", "INC-1"));

    // Rust attenuates a Python mandate; the result narrows and keeps its family id.
    let output = bm(
        dir.path(),
        &[
            "attenuate",
            "--token",
            "mandate.b64",
            "--authority-pub",
            "authority.pub",
            "--resource",
            "/projets/acme/x/",
        ],
    );
    assert!(output.status.success(), "{}", stderr(&output));
    let ours = stdout(&output).trim().to_owned();
    assert_eq!(
        ops::capability_key(&ours).unwrap(),
        ops::capability_key(&mandate).unwrap()
    );
    assert!(!allowed(&v, &ours, "/projets/acme/a.txt", "INC-1"));
    assert!(allowed(&v, &ours, "/projets/acme/x/a.txt", "INC-1"));
}

#[test]
fn rust_extends_a_python_revocation_list() {
    let (dir, _) = fixtures();
    let authority_pub = read(dir.path(), "authority.pub");
    let output = bm(
        dir.path(),
        &[
            "revoke",
            "--key",
            "authority.key",
            "--out",
            "revoked.list",
            "--add",
            "jti:rust",
            "--from-token",
            "narrowed.b64",
        ],
    );
    assert!(output.status.success(), "{}", stderr(&output));
    assert_eq!(
        stdout(&output).trim(),
        "revocation list revoked.list now has 3 id(s)"
    );
    let doc = strict_json(std::fs::read(dir.path().join("revoked.list")).unwrap()).unwrap();
    validate_document(&doc, &authority_pub, None, true).unwrap();
    let revoked: Vec<&str> = doc["revoked"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_str().unwrap())
        .collect();
    let family = ops::capability_key(&read(dir.path(), "mandate.b64")).unwrap();
    assert!(revoked.contains(&"jti:python") && revoked.contains(&"jti:rust"));
    assert!(revoked.contains(&family.as_str()));
}

#[test]
fn rust_verifies_and_resumes_a_python_audit_chain() {
    let (dir, _) = fixtures();
    let output = bm(
        dir.path(),
        &["audit-verify", "--log", "audit.log", "--pub", "audit.pub"],
    );
    assert!(output.status.success(), "{}", stderr(&output));
    assert!(stdout(&output).contains("chain intact"));
    let output = bm(
        dir.path(),
        &["audit-head", "--log", "audit.log", "--key", "audit.key"],
    );
    assert!(output.status.success(), "{}", stderr(&output));
    let head = strict_json(stdout(&output).trim()).unwrap();
    let public = read(dir.path(), "audit.pub");
    assert!(verify_head_attestation(&head, &public));
    assert_eq!(head["gateway_id"], json!("gw-python"));
    assert_eq!(head["seq"], json!(2));

    let path = dir.path().join("audit.log");
    let private = keys::load_private_key(dir.path().join("audit.key"), None).unwrap();
    AuditLog::new(
        &path,
        &private,
        "gw-python",
        "rust-digest",
        TrustedKeys::new(),
    )
    .unwrap()
    .record(Record {
        decision: "ALLOW".into(),
        ..Default::default()
    })
    .unwrap();
    let result = verify_log(&path, &trusted_from(&[public]).unwrap()).unwrap();
    assert!(result.ok && result.entries == 4);
}

#[test]
fn rust_writes_into_a_python_registry_store() {
    let (dir, _) = fixtures();
    let store = Store::new(dir.path().join("agents.json"));
    let agent = store.get("interop-agent").unwrap().unwrap();
    assert_eq!(agent["agent_pubkey"], json!(read(dir.path(), "agent.pub")));
    assert_eq!(agent["owner_ref"], json!("python"));

    let other = keys::generate_keypair().public_str;
    let conflict = bm(
        dir.path(),
        &[
            "registry-add",
            "--agent-id",
            "interop-agent",
            "--pubkey",
            &other,
            "--store",
            "agents.json",
        ],
    );
    assert_eq!(conflict.status.code(), Some(1));
    let added = bm(
        dir.path(),
        &[
            "registry-add",
            "--agent-id",
            "rust-agent",
            "--pubkey",
            &other,
            "--store",
            "agents.json",
        ],
    );
    assert!(added.status.success(), "{}", stderr(&added));
    let stored = strict_json(std::fs::read(dir.path().join("agents.json")).unwrap()).unwrap();
    assert_eq!(stored.as_object().unwrap().len(), 2);
    // The Python record's sequence number only moves forward.
    let previous = agent["seq"].as_i64().unwrap();
    store
        .put(
            "interop-agent",
            json!({"agent_pubkey": read(dir.path(), "agent.pub")})
                .as_object()
                .unwrap()
                .clone(),
            false,
        )
        .unwrap();
    assert!(
        store.get("interop-agent").unwrap().unwrap()["seq"]
            .as_i64()
            .unwrap()
            > previous
    );
}
